ARG BASE_IMAGE=louislam/uptime-kuma:base2

FROM louislam/uptime-kuma:base2 AS build
USER node
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

# Nur die für npm nötigen Files zuerst kopieren
COPY --chown=node:node package.json package-lock.json .npmrc ./

# Alle Dependencies (inkl. dev) installieren, damit "npm run build" funktioniert
RUN npm ci

# Restlichen Code kopieren (inkl. deiner Änderungen)
COPY --chown=node:node . .

# Frontend bauen -> erzeugt /app/dist/**
RUN npm run build

# Datenverzeichnis für später (wird von Volume übermountet, aber schadet nicht)
RUN mkdir -p ./data


FROM $BASE_IMAGE AS release
WORKDIR /app
LABEL org.opencontainers.image.source="https://github.com/louislam/uptime-kuma"
ENV UPTIME_KUMA_IS_CONTAINER=1
COPY --chown=node:node --from=build /app /app
EXPOSE 3001
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD extra/healthcheck
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "server/server.js"]
